/* Sahulat Guide — government universities, entry tests, admission criteria and fees.
 * Hand-maintained. Checked 6 Oct 2026. Every figure carries its source and a confidence label:
 *   official  = university / test body's own page or PDF
 *   news      = national newspaper or news site reporting the official notice
 *   secondary = education portal (Maqsad, ilmkidunya, Eduvision…) — verify before relying on it
 *   old       = official but from an earlier session
 * Never add a number you can't source. Write "Not published" instead.
 */
window.UNI = {
checked: "2026-10-06",

/* Entry tests. ev = dated events [ISO date, kind, label]; kind: open | close | test | result.
   next = what to expect when dates aren't announced yet. */
tests: [
{ id:"mdcat", name:"MDCAT", full:"Medical & Dental College Admission Test", body:"PM&DC (held by UHS in Punjab, Sukkur IBA in Sindh, KMU in KP, BUMHS in Balochistan)",
  for:"MBBS and BDS at every public and private medical and dental college", field:"med",
  ev:[["2026-06-22","open","Registration opened"],["2026-07-08","close","Registration closed (late fee till 13 Jul)"],["2026-09-20","test","MDCAT 2026 held (moved from 16 Aug)"],["2026-09-25","result","UHS (Punjab) result, 66% passed"]],
  next:"MDCAT 2027 expected Aug–Sep 2027; registration usually opens in June–July.",
  fee:"PKR 9,000 (late PKR 13,000); Riyadh centre PKR 45,000",
  format:"180 MCQs, 3 hours, paper-based, no negative marking: Biology 81, Chemistry 45, Physics 36, English 9, Logical reasoning 9",
  pass:"MBBS 55%, BDS 50%",
  merit:"Matric + FSc + MDCAT aggregate. Punjab (UHS) is reported as Matric 10%, FSc 40%, MDCAT 50%. Other provinces set their own weightage.",
  elig:"At least 65% in FSc Pre-Medical (PMDC rule for 2025-26)",
  url:"https://mdcat.pmdc.pk", src:[["Dawn","https://www.dawn.com/news/2020995"],["Daily Times (result)","https://dailytimes.com.pk/1557861/mdcat-2026-result-announced-success-ratio-remains-66/"]], conf:"news" },

{ id:"net", name:"NUST NET", full:"NUST Entry Test 2027", body:"NUST",
  for:"All NUST undergraduate programmes: engineering, computing, sciences, business, social sciences, architecture", field:"eng",
  ev:[["2026-10-04","open","Series 1 registration opened"],["2026-11-14","close","Series 1 registration closes"],["2026-11-17","test","Series 1 tests begin (computer-based, Islamabad)"],["2027-04-20","open","ACT/SAT-basis applications open (till 25 Jul)"]],
  next:"Series 2: tests Jan–Feb 2027 (Islamabad), Mar 2027 (Karachi, Quetta, Gilgit). Series 3: Apr 2027. Series 4: Jun–Jul 2027. Each series has its own registration.",
  fee:"PKR 5,000 per series (USD 40 from abroad)",
  format:"200 MCQs, 3 hours, computer-based, no negative marking. Engineering: Maths 50%, Physics 30%, English 20%. Applied sciences: Biology 50%, Chemistry 30%, English 20%. Business: Quantitative 50%, English 50%.",
  pass:"Not published",
  merit:"NET 75% + FSc Part-I 15% + Matric 10%. Your best series counts.",
  elig:"60% in Matric and FSc Part-I for engineering and computing",
  url:"https://ugadmissions.nust.edu.pk", src:[["NUST: dates to remember","https://nust.edu.pk/admissions/undergraduates/dates-to-remember/"]], conf:"official" },

{ id:"ecat", name:"ECAT", full:"Engineering College Admission Test (UET Lahore)", body:"UET Lahore",
  for:"UET Lahore and its campuses, and Punjab public engineering universities that use ECAT (e.g. University of Gujrat)", field:"eng",
  ev:[["2026-03-30","test","ECAT-1 2026 held (30 Mar – 3 Apr)"],["2026-06-09","close","ECAT-2 registration closed"],["2026-06-16","test","ECAT-2 2026 held (16–21 Jun)"],["2026-06-23","result","ECAT-2 result"]],
  next:"2027 dates not announced. Expect ECAT-1 around Mar–Apr 2027 and ECAT-2 around Jun 2027.",
  fee:"PKR 3,000 per attempt",
  format:"100 MCQs in 100 minutes, no negative marking: Maths or Biology 30, Physics 30, Chemistry or Computer 30, English 10",
  pass:"Not published",
  merit:"FSc 50% + ECAT 33% + Matric 17%. Best of the two ECATs counts.",
  elig:"60% in FSc Pre-Engineering (50% for computer science)",
  url:"https://ecat.uet.edu.pk", src:[["UET Lahore notice","https://www.uet.edu.pk/newsannouncement/Event/ECAT-Phase-Two-Registration-Open-for-Fall-2026-Admissions-2026.05.14/?instancedate=1778742457000"]], conf:"official" },

{ id:"etea", name:"ETEA Engineering", full:"ETEA entry test for engineering (KP)", body:"Educational Testing & Evaluation Agency, KP",
  for:"UET Peshawar and KP public engineering programmes", field:"eng",
  ev:[["2026-07-04","test","ETEA Test-I held (4–5 Jul)"],["2026-07-25","test","ETEA Test-II held (25–26 Jul)"]],
  next:"2027 expected Jun–Jul 2027. KP medical admissions now use MDCAT (held by KMU), not a separate ETEA test.",
  fee:"PKR 1,000 per test",
  format:"Computer-based, no negative marking. Pre-engineering: 100 MCQs (Physics 40, Maths 35, English 15, Chemistry/Computer 10)",
  pass:"Not published",
  merit:"UET Peshawar is reported as ETEA 50% + FSc 40% + Matric 10% (secondary source)",
  elig:"60% in FSc Pre-Engineering (PEC rule)",
  url:"https://etea.edu.pk", src:[["Result.pk","https://www.result.pk/educom/etea-computer-based-entrance-test-2026-for-engineering-admissions-59928.htm"]], conf:"secondary" },

{ id:"usat", name:"HEC USAT", full:"Undergraduate Studies Admission Test", body:"HEC Education Testing Council",
  for:"BS admissions at universities that accept USAT (e.g. Quaid-i-Azam University)", field:"gen",
  ev:[["2026-07-26","test","USAT for QAU admissions"],["2026-10-27","open","Registration opens"],["2026-11-10","close","Registration closes"],["2026-12-07","test","Next USAT"]],
  next:"Held several times a year. Check etc.hec.gov.pk for the next session.",
  fee:"PKR 1,200",
  format:"Choose your stream: USAT-A (Arts), COM (Commerce), CS, E (Pre-Engineering), GS (General Science), M (Pre-Medical). 75 MCQs in 100 minutes (verbal 35, quantitative 40) plus a 40-minute essay in English or Urdu.",
  pass:"50 out of 100",
  merit:"Set by each university",
  elig:"Intermediate or equivalent (appearing students can sit)",
  url:"https://etc.hec.gov.pk", src:[["GoTest (schedule)","https://gotest.com.pk/admissions/hec-usat-test-schedule-dates-registration-online/"]], conf:"secondary" },

{ id:"lat", name:"HEC LAT", full:"Law Admission Test", body:"HEC Education Testing Council",
  for:"LLB (5-year) at every university and law college", field:"law",
  ev:[],
  next:"Held several times a year. Sessions and fee are announced on etc.hec.gov.pk.",
  fee:"See etc.hec.gov.pk", format:"Set by HEC; see etc.hec.gov.pk", pass:"50% (University of Sindh states 50% minimum)", merit:"Set by each university",
  elig:"Intermediate, usually 45% or more",
  url:"https://etc.hec.gov.pk", src:[["University of Sindh advertisement","https://admission.usindh.edu.pk/admission/assets/advertisement_2027.pdf"]], conf:"official" },

{ id:"nat", name:"NTS NAT", full:"National Aptitude Test", body:"National Testing Service",
  for:"Undergraduate admissions at COMSATS, IST and other universities that accept NAT", field:"gen",
  ev:[["2026-10-11","test","NAT-X"],["2026-10-19","close","NAT-XI registration closes"],["2026-11-15","test","NAT-XI"],["2026-12-07","close","NAT-XII registration closes"],["2026-12-13","test","NAT-XII"]],
  next:"Held almost every month. A result stays valid for one year.",
  fee:"About PKR 1,510 (secondary)",
  format:"100 MCQs, 2 hours, paper-based. Categories IE (engineering), IM (medical), ICS, ICOM, IA (arts), IGS",
  pass:"50%",
  merit:"Set by each university",
  elig:"Intermediate or appearing",
  url:"https://www.nts.org.pk", src:[["ilmkidunya (schedule)","https://www.ilmkidunya.com/nts/nts-test-schedule"]], conf:"secondary" },

{ id:"gat", name:"NTS GAT", full:"Graduate Assessment Test (MS/MPhil/PhD)", body:"National Testing Service",
  for:"MS, MPhil and PhD admissions", field:"gen",
  ev:[["2026-10-11","test","GAT-General"],["2026-10-12","close","GAT-Subject registration closes"],["2026-11-15","test","GAT-Subject"],["2026-12-13","test","GAT-General"]],
  next:"Several sessions a year.", fee:"GAT-Subject PKR 1,500", format:"See nts.org.pk", pass:"50%", merit:"Set by each university", elig:"16 years of education",
  url:"https://www.nts.org.pk", src:[["ilmkidunya (schedule)","https://www.ilmkidunya.com/nts/nts-test-schedule"]], conf:"secondary" },

{ id:"pieas", name:"PIEAS test", full:"PIEAS BS admission test", body:"PIEAS, Islamabad",
  for:"BS engineering and sciences at PIEAS", field:"eng",
  ev:[["2026-06-12","close","Second test registration closed"],["2026-07-12","test","Second test 2026"]],
  next:"2027 test expected in spring–summer 2027.",
  fee:"PKR 3,500", format:"PIEAS's own test, 100 MCQs in 3 hours", pass:"Not published", merit:"Not published",
  elig:"60% in both Matric and Intermediate",
  url:"https://admissions.pieas.edu.pk", src:[["PIEAS leaflet 2026","https://admissions.pieas.edu.pk/Admissions/Contents/Information%20leaflet%20BS-Programs-Updated_02012026.pdf"],["ProPakistani","https://propakistani.pk/edunation/admissions/pieas-bs-second-test-mphil-phd-admissions-2026/"]], conf:"official" },

{ id:"ist", name:"IST", full:"Institute of Space Technology admissions", body:"IST, Islamabad",
  for:"IST engineering programmes (computing and sciences don't need a test)", field:"eng",
  ev:[["2026-04-15","open","Applications opened"],["2026-06-30","close","Applications closed"]],
  next:"Applications usually open mid-April. IST accepts NAT, NET, ECAT, NED, MUET or its own test score.",
  fee:"Not published", format:"Uses another test's score", pass:"At least 33% (secondary)", merit:"Matric + FSc Part-I + test; weightage not published",
  elig:"Engineering: 60% in Matric and FSc Pre-Engineering",
  url:"https://www.ist.edu.pk", src:[["Maqsad guide","https://blog.maqsad.io/blog/ist-admission-guide"]], conf:"secondary" },

{ id:"iba", name:"IBA Karachi test", full:"IBA Karachi aptitude test (Fall 2027 intake)", body:"IBA Karachi",
  for:"BBA, BS Accounting & Finance, Economics, Computer Science, Mathematics and other IBA programmes", field:"bus",
  ev:[["2026-12-09","close","Round 1 forms due"],["2026-12-20","test","Round 1 test"],["2027-03-08","close","Round 2 forms due"],["2027-03-21","test","Round 2 test"],["2027-06-09","close","Round 3 forms due"],["2027-06-20","test","Round 3 test"]],
  next:"Three rounds; you can sit more than one.",
  fee:"Charged per school you apply to; see the IBA site", format:"English and mathematics aptitude (details on the IBA site)", pass:"Not published", merit:"Not published",
  elig:"Intermediate or A-levels (see IBA criteria)",
  url:"https://admissions.iba.edu.pk/admissions_schedule.php", src:[["IBA admissions schedule","https://admissions.iba.edu.pk/admissions_schedule.php"]], conf:"official" },

{ id:"sukkur", name:"Sukkur IBA test", full:"Sukkur IBA University undergraduate test", body:"Sukkur IBA University",
  for:"BBA, BS and BE programmes at Sukkur IBA", field:"bus",
  ev:[["2026-07-05","test","Phase-II test 2026 (date reported as 5 or 13 Jul)"]],
  next:"2027 Phase-I applications expected around April 2027.",
  fee:"PKR 2,500", format:"English, mathematics and IQ sections", pass:"Not published", merit:"Not published", elig:"Intermediate",
  url:"https://applyadmission.iba-suk.edu.pk", src:[["GoTest","https://gotest.com.pk/admissions/iba-sukkur-university-admission/"]], conf:"secondary" },

{ id:"ned", name:"NED test", full:"NED University entry test", body:"NED UET, Karachi",
  for:"Undergraduate engineering and other programmes at NED", field:"eng",
  ev:[["2026-03-30","open","Applications opened"],["2026-05-29","close","Applications closed"],["2026-06-12","test","Phase I test (12–15 Jun)"],["2026-07-06","test","Phase II test (6–8 Jul)"]],
  next:"2027 applications expected Mar–May 2027, tests in Jun–Jul.",
  fee:"About PKR 2,500 (secondary)", format:"100 MCQs, 2 hours, computer-based, 4 sections", pass:"50%",
  merit:"Test 60% + HSC Part-I 40%",
  elig:"60% in HSC Pre-Engineering",
  url:"https://www.neduet.edu.pk/admission", src:[["NED FAQ 2026","https://www.neduet.edu.pk/sites/default/files/Admissions-2026/FAQ.pdf"],["ProPakistani","https://propakistani.pk/2026/03/27/ned-university-announces-admissions-schedule-for-2026-27/"]], conf:"official" },

{ id:"muet", name:"MUET test", full:"MUET pre-admission test", body:"Mehran UET, Jamshoro",
  for:"BE and BS at MUET Jamshoro and its campuses", field:"eng",
  ev:[["2026-04-15","open","Applications opened"],["2026-05-05","close","Documents due"],["2026-05-22","test","District-wise tests from 22 May"]],
  next:"2027 applications expected mid-April 2027, tests from late May.",
  fee:"Not published", format:"Computer-based", pass:"Not published", merit:"Not published", elig:"Intermediate Pre-Engineering (see advertisement)",
  url:"https://admissions.muet.edu.pk", src:[["MUET advertisement 2026-27","https://www.muet.edu.pk/sites/default/files/documents/2026-04/14-04-2026-Detailed-Admission-Advertisement-for-Academic-Session-2026-27-26-Batch_0.pdf"]], conf:"official" },

{ id:"usindh", name:"Sindh University test", full:"University of Sindh pre-entry test (Admissions 2027)", body:"University of Sindh, Jamshoro",
  for:"Bachelor programmes at Jamshoro and campuses (LLB uses HEC LAT)", field:"gen",
  ev:[["2026-08-10","open","Registration opened"],["2026-09-11","close","Registration closed"],["2026-10-04","test","Pre-entry test, day 1"],["2026-10-11","test","Pre-entry test, day 2"]],
  next:"Merit lists follow the test.",
  fee:"PKR 3,000", format:"Not published", pass:"40%", merit:"Not published", elig:"Intermediate",
  url:"https://admission.usindh.edu.pk", src:[["Admissions 2027 advertisement","https://admission.usindh.edu.pk/admission/assets/advertisement_2027.pdf"]], conf:"official" },

{ id:"uok", name:"Karachi University", full:"University of Karachi admissions 2027", body:"University of Karachi",
  for:"Most BS programmes are on open merit (no test); some departments, Pharm-D and Visual Studies hold entry tests", field:"gen",
  ev:[["2026-10-12","open","Open-merit BS applications open"],["2026-10-21","close","Open-merit applications close"]],
  next:"Entry-test dates for test-based departments are announced on uokadmission.edu.pk (usually Nov–Dec).",
  fee:"Not published", format:"Department tests: see prospectus", pass:"Not published", merit:"Open merit on Intermediate marks for most programmes", elig:"Intermediate",
  url:"https://uokadmission.edu.pk", src:[["KU prospectus 2027","https://uokadmission.edu.pk/2027/prospectus/MP2027.pdf"],["ProPakistani","https://propakistani.pk/2026/09/24/karachi-university-announces-open-merit-bs-admissions-2026/"]], conf:"official" },

{ id:"pu", name:"PU entry test", full:"University of the Punjab undergraduate entry test", body:"University of the Punjab, Lahore",
  for:"All PU undergraduate programmes (7 test types; LLB also needs LAT)", field:"gen",
  ev:[["2026-05-25","close","First test registration closed"],["2026-06-14","test","First test"],["2026-07-03","close","Second test registration closed"],["2026-07-19","test","Second test"]],
  next:"2027 tests expected Jun–Jul 2027.",
  fee:"PKR 2,500 (secondary)", format:"100 MCQs: verbal, quantitative and three subject sections of 20 each", pass:"Not published",
  merit:"Entry test counts 25% of merit", elig:"Intermediate (programme-wise minimums in the prospectus)",
  url:"https://admissiontest.pu.edu.pk", src:[["PU press release","https://pu.edu.pk/home/section/allpress/17002"],["Eduvision","https://www.eduvision.edu.pk/edu_news/pu-announces-schedule-for-entry-test-2026-news-3871"]], conf:"official" },

{ id:"uaf", name:"UAF test", full:"University of Agriculture Faisalabad entry test", body:"UAF",
  for:"UAF undergraduate programmes", field:"agri",
  ev:[["2026-06-22","close","First test registration closed"],["2026-07-05","test","First test"],["2026-07-24","close","Second test registration closed"],["2026-08-02","test","Second test (13 centres in Punjab)"]],
  next:"2027 expected Jul–Aug 2027.",
  fee:"Not published", format:"Not published", pass:"Not published", merit:"Not published", elig:"Intermediate",
  url:"https://web.uaf.edu.pk", src:[["Result.pk","https://www.result.pk/educom/uaf-admissions-2026-entry-test-schedule-updates-59876.htm"]], conf:"secondary" },

{ id:"qau", name:"QAU", full:"Quaid-i-Azam University BS admissions", body:"QAU (test through HEC USAT)",
  for:"BS, LLB and Pharm-D morning programmes at QAU", field:"gen",
  ev:[["2026-07-26","test","USAT for QAU"],["2026-08-10","close","QAU applications closed"]],
  next:"Fall 2027 applications expected Jun–Jul 2027.",
  fee:"USAT fee", format:"HEC USAT", pass:"USAT 50", merit:"Matric 30% + HSSC 70% (Fall 2024 policy)", elig:"50% in HSSC Part-I",
  url:"https://qau.edu.pk", src:[["24 News","https://www.24newshd.tv/30-Jun-2026/quaid-i-azam-university-unveils-dates-schedule-admissions-2026"],["QAU notice 2024","https://qau.edu.pk/admissions-for-undergraduate-bs-ba-llb-pharm-d-morning-programme-on-regular-self-finance-basis-fall-semester-2024/"]], conf:"news" },

{ id:"comsats", name:"COMSATS", full:"COMSATS University admissions (NAT-based)", body:"COMSATS University Islamabad",
  for:"Undergraduate programmes on all COMSATS campuses", field:"gen",
  ev:[["2026-05-31","open","Fall 2026 applications opened"],["2026-08-14","close","Fall 2026 last campus deadline"]],
  next:"Spring 2027 intake usually opens Dec–Jan. Sit an NTS NAT first.",
  fee:"NAT fee", format:"NTS NAT", pass:"NAT 50%", merit:"Not published", elig:"50% Intermediate (CS needs Maths); 60% for engineering",
  url:"https://admissions.comsats.edu.pk", src:[["Maqsad guide","https://blog.maqsad.io/blog/comsats-university-admission"]], conf:"secondary" },

{ id:"aiou", name:"AIOU", full:"Allama Iqbal Open University admissions", body:"AIOU",
  for:"Matric, FA, associate degree, BS, B.Ed and other distance programmes", field:"dist",
  ev:[["2026-07-01","open","Autumn 2026 admissions opened"],["2026-10-06","close","Autumn 2026 extended deadline (late fee)"]],
  next:"Spring 2027 admissions expected to open around January 2027. No entry test.",
  fee:"Varies by programme", format:"No test", pass:"—", merit:"—", elig:"Previous level passed",
  url:"https://aiou.edu.pk", src:[["ProPakistani","https://propakistani.pk/2026/09/24/aiou-extends-autumn-2026-admission-deadline/"]], conf:"news" }
],

/* Government universities: [id, name, city, province, type, website or "", tests] */
unis: [
/* Punjab */
["pu","University of the Punjab","Lahore","pb","gen","pu.edu.pk","pu"],
["uet","UET Lahore (University of Engineering & Technology)","Lahore","pb","eng","uet.edu.pk","ecat"],
["gcu","GC University Lahore","Lahore","pb","gen","gcu.edu.pk",""],
["lcwu","Lahore College for Women University","Lahore","pb","women","lcwu.edu.pk",""],
["kinnaird","Kinnaird College for Women University","Lahore","pb","women","kinnaird.edu.pk",""],
["ue","University of Education","Lahore","pb","gen","ue.edu.pk",""],
["itu","Information Technology University","Lahore","pb","eng","itu.edu.pk",""],
["nca","National College of Arts","Lahore","pb","arts","nca.edu.pk",""],
["uhe","University of Home Economics","Lahore","pb","women","uhe.edu.pk",""],
["ptut","Punjab Tianjin University of Technology","Lahore","pb","eng","ptut.edu.pk",""],
["uhs","University of Health Sciences (MBBS admissions in Punjab)","Lahore","pb","med","uhs.edu.pk","mdcat"],
["kemu","King Edward Medical University","Lahore","pb","med","kemu.edu.pk","mdcat"],
["fjmu","Fatima Jinnah Medical University","Lahore","pb","med","fjmu.edu.pk","mdcat"],
["uchs","University of Child Health Sciences","Lahore","pb","med","uchs.edu.pk",""],
["uvas","University of Veterinary & Animal Sciences","Lahore","pb","vet","uvas.edu.pk",""],
["pifd","Pakistan Institute of Fashion & Design","Lahore","pb","arts","pifd.edu.pk",""],
["vu","Virtual University of Pakistan","Lahore","pb","dist","vu.edu.pk",""],
["fjwu","Fatima Jinnah Women University","Rawalpindi","pb","women","fjwu.edu.pk",""],
["rwu","Rawalpindi Women University","Rawalpindi","pb","women","rwu.edu.pk",""],
["rmu","Rawalpindi Medical University","Rawalpindi","pb","med","rmur.edu.pk","mdcat"],
["uaar","PMAS Arid Agriculture University","Rawalpindi","pb","agri","uaar.edu.pk",""],
["nums","National University of Medical Sciences (NUMS)","Rawalpindi","pb","med","numspak.edu.pk","mdcat"],
["kum","Kohsar University Murree","Murree","pb","gen","",""],
["uettaxila","UET Taxila","Taxila","pb","eng","uettaxila.edu.pk","ecat"],
["uoc","University of Chakwal","Chakwal","pb","gen","uoc.edu.pk",""],
["uaf","University of Agriculture Faisalabad","Faisalabad","pb","agri","uaf.edu.pk","uaf"],
["gcuf","GC University Faisalabad","Faisalabad","pb","gen","gcuf.edu.pk",""],
["gcwuf","Government College Women University Faisalabad","Faisalabad","pb","women","gcwuf.edu.pk",""],
["ntu","National Textile University","Faisalabad","pb","eng","ntu.edu.pk",""],
["fmu","Faisalabad Medical University","Faisalabad","pb","med","fmu.edu.pk","mdcat"],
["uoj","University of Jhang","Jhang","pb","gen","",""],
["uos","University of Sargodha","Sargodha","pb","gen","su.edu.pk",""],
["umw","University of Mianwali","Mianwali","pb","gen","umw.edu.pk",""],
["thal","Thal University Bhakkar","Bhakkar","pb","gen","",""],
["uog","University of Gujrat","Gujrat","pb","gen","uog.edu.pk","ecat"],
["gcwus","Government College Women University Sialkot","Sialkot","pb","women","gcwus.edu.pk",""],
["uon","University of Narowal","Narowal","pb","gen","uon.edu.pk",""],
["bgnu","Baba Guru Nanak University","Nankana Sahib","pb","gen","bgnu.edu.pk",""],
["uo","University of Okara","Okara","pb","gen","uo.edu.pk",""],
["uosahiwal","University of Sahiwal","Sahiwal","pb","gen","uosahiwal.edu.pk",""],
["bzu","Bahauddin Zakariya University","Multan","pb","gen","bzu.edu.pk",""],
["mnsuet","MNS University of Engineering & Technology","Multan","pb","eng","mnsuet.edu.pk","ecat"],
["mnsuam","MNS University of Agriculture","Multan","pb","agri","mnsuam.edu.pk",""],
["wum","Women University Multan","Multan","pb","women","wum.edu.pk",""],
["emerson","Emerson University Multan","Multan","pb","gen","",""],
["nmu","Nishtar Medical University","Multan","pb","med","nmu.edu.pk","mdcat"],
["gudgk","Ghazi University","Dera Ghazi Khan","pb","gen","gudgk.edu.pk",""],
["iub","Islamia University of Bahawalpur","Bahawalpur","pb","gen","iub.edu.pk",""],
["gscwu","Government Sadiq College Women University","Bahawalpur","pb","women","gscwu.edu.pk",""],
["cuvas","Cholistan University of Veterinary & Animal Sciences","Bahawalpur","pb","vet","cuvas.edu.pk",""],
["kfueit","Khwaja Fareed University of Engineering & IT","Rahim Yar Khan","pb","eng","kfueit.edu.pk","ecat"],
/* Sindh */
["uok","University of Karachi","Karachi","sd","gen","uok.edu.pk","uok"],
["ned","NED University of Engineering & Technology","Karachi","sd","eng","neduet.edu.pk","ned"],
["iba","Institute of Business Administration (IBA) Karachi","Karachi","sd","bus","iba.edu.pk","iba"],
["duhs","Dow University of Health Sciences","Karachi","sd","med","duhs.edu.pk","mdcat"],
["jsmu","Jinnah Sindh Medical University","Karachi","sd","med","jsmu.edu.pk","mdcat"],
["duet","Dawood University of Engineering & Technology","Karachi","sd","eng","duet.edu.pk",""],
["smiu","Sindh Madressatul Islam University","Karachi","sd","gen","smiu.edu.pk",""],
["szabul","Shaheed Zulfiqar Ali Bhutto University of Law","Karachi","sd","law","szabul.edu.pk","lat"],
["bbsul","Benazir Bhutto Shaheed University Lyari","Karachi","sd","gen","bbsul.edu.pk",""],
["fuuast","Federal Urdu University of Arts, Science & Technology","Karachi","sd","gen","fuuast.edu.pk",""],
["usindh","University of Sindh","Jamshoro","sd","gen","usindh.edu.pk","usindh"],
["muet","Mehran University of Engineering & Technology","Jamshoro","sd","eng","muet.edu.pk","muet"],
["lumhs","Liaquat University of Medical & Health Sciences","Jamshoro","sd","med","lumhs.edu.pk","mdcat"],
["gcuh","Government College University Hyderabad","Hyderabad","sd","gen","gcuh.edu.pk",""],
["sau","Sindh Agriculture University","Tando Jam","sd","agri","sau.edu.pk",""],
["sukkur","Sukkur IBA University","Sukkur","sd","bus","iba-suk.edu.pk","sukkur"],
["bnbwu","Begum Nusrat Bhutto Women University","Sukkur","sd","women","bnbwu.edu.pk",""],
["salu","Shah Abdul Latif University","Khairpur","sd","gen","salu.edu.pk",""],
["quest","Quaid-e-Awam University of Engineering, Science & Technology","Nawabshah","sd","eng","quest.edu.pk",""],
["pumhs","Peoples University of Medical & Health Sciences for Women","Nawabshah","sd","med","pumhs.edu.pk","mdcat"],
["sbbusba","Shaheed Benazir Bhutto University","Shaheed Benazirabad","sd","gen","sbbusba.edu.pk",""],
["smbbmu","Shaheed Mohtarma Benazir Bhutto Medical University","Larkana","sd","med","smbbmu.edu.pk","mdcat"],
["sayu","Shaikh Ayaz University","Shikarpur","sd","gen","",""],
["usms","University of Sufism & Modern Sciences","Bhit Shah","sd","gen","",""],
/* Khyber Pakhtunkhwa */
["uop","University of Peshawar","Peshawar","kp","gen","uop.edu.pk",""],
["uetp","UET Peshawar","Peshawar","kp","eng","uetpeshawar.edu.pk","etea"],
["kmu","Khyber Medical University (MBBS admissions in KP)","Peshawar","kp","med","kmu.edu.pk","mdcat"],
["icp","Islamia College University","Peshawar","kp","gen","icp.edu.pk",""],
["aup","University of Agriculture Peshawar","Peshawar","kp","agri","aup.edu.pk",""],
["sbbwu","Shaheed Benazir Bhutto Women University","Peshawar","kp","women","sbbwu.edu.pk",""],
["imsciences","Institute of Management Sciences","Peshawar","kp","bus","imsciences.edu.pk",""],
["uotn","University of Technology Nowshera","Nowshera","kp","eng","",""],
["awkum","Abdul Wali Khan University","Mardan","kp","gen","awkum.edu.pk",""],
["wumardan","Women University Mardan","Mardan","kp","women","wumardan.edu.pk",""],
["bkuc","Bacha Khan University","Charsadda","kp","gen","bkuc.edu.pk",""],
["uoswabi","University of Swabi","Swabi","kp","gen","uoswabi.edu.pk",""],
["wus","Women University Swabi","Swabi","kp","women","",""],
["uom","University of Malakand","Chakdara","kp","gen","uom.edu.pk",""],
["swat","University of Swat","Swat","kp","gen","swat.edu.pk",""],
["sbbu","Shaheed Benazir Bhutto University Sheringal","Upper Dir","kp","gen","sbbu.edu.pk",""],
["uoch","University of Chitral","Chitral","kp","gen","uoch.edu.pk",""],
["ubuner","University of Buner","Buner","kp","gen","ubuner.edu.pk",""],
["hu","Hazara University","Mansehra","kp","gen","hu.edu.pk",""],
["uoh","University of Haripur","Haripur","kp","gen","uoh.edu.pk",""],
["pafiast","Pak-Austria Fachhochschule Institute of Applied Sciences & Technology","Haripur","kp","eng","paf-iast.edu.pk",""],
["kust","Kohat University of Science & Technology","Kohat","kp","gen","kust.edu.pk",""],
["kkkuk","Khushal Khan Khattak University","Karak","kp","gen","kkkuk.edu.pk",""],
["ustb","University of Science & Technology Bannu","Bannu","kp","gen","ustb.edu.pk",""],
["ulm","University of Lakki Marwat","Lakki Marwat","kp","gen","ulm.edu.pk",""],
["gu","Gomal University","Dera Ismail Khan","kp","gen","gu.edu.pk",""],
/* Balochistan */
["uob","University of Balochistan","Quetta","bl","gen","uob.edu.pk",""],
["buitems","BUITEMS (Balochistan University of IT, Engineering & Management Sciences)","Quetta","bl","eng","buitms.edu.pk",""],
["sbkwu","Sardar Bahadur Khan Women's University","Quetta","bl","women","sbkwu.edu.pk",""],
["bumhs","Bolan University of Medical & Health Sciences","Quetta","bl","med","bumhs.edu.pk","mdcat"],
["buetk","Balochistan UET Khuzdar","Khuzdar","bl","eng","buetk.edu.pk",""],
["luawms","Lasbela University of Agriculture, Water & Marine Sciences","Uthal","bl","agri","luawms.edu.pk",""],
["uot","University of Turbat","Turbat","bl","gen","uot.edu.pk",""],
["ulor","University of Loralai","Loralai","bl","gen","",""],
["mckru","Mir Chakar Khan Rind University","Sibi","bl","gen","",""],
["ugwadar","University of Gwadar","Gwadar","bl","gen","",""],
/* Islamabad (federal) */
["qau","Quaid-i-Azam University","Islamabad","ict","gen","qau.edu.pk","qau"],
["nust","NUST (National University of Sciences & Technology)","Islamabad","ict","eng","nust.edu.pk","net"],
["comsats","COMSATS University Islamabad","Islamabad (7 campuses)","ict","gen","comsats.edu.pk","comsats"],
["pieas","PIEAS (Pakistan Institute of Engineering & Applied Sciences)","Islamabad","ict","eng","pieas.edu.pk","pieas"],
["ist","Institute of Space Technology","Islamabad","ict","eng","ist.edu.pk","ist"],
["iiui","International Islamic University","Islamabad","ict","gen","iiu.edu.pk",""],
["air","Air University","Islamabad","ict","eng","au.edu.pk",""],
["bahria","Bahria University","Islamabad (also Lahore, Karachi)","ict","gen","bahria.edu.pk",""],
["numl","National University of Modern Languages","Islamabad","ict","gen","numl.edu.pk",""],
["aiou","Allama Iqbal Open University","Islamabad","ict","dist","aiou.edu.pk","aiou"],
["ndu","National Defence University","Islamabad","ict","gen","ndu.edu.pk",""],
["pide","Pakistan Institute of Development Economics","Islamabad","ict","gen","pide.org.pk",""],
["szabmu","Shaheed Zulfiqar Ali Bhutto Medical University","Islamabad","ict","med","szabmu.edu.pk",""],
["nutech","National University of Technology (NUTECH)","Islamabad","ict","eng","nutech.edu.pk",""],
["nsu","National Skills University","Islamabad","ict","eng","nsu.edu.pk",""],
["hsa","Health Services Academy","Islamabad","ict","med","hsa.edu.pk",""],
/* Gilgit-Baltistan */
["kiu","Karakoram International University","Gilgit","gb","gen","kiu.edu.pk",""],
["uobs","University of Baltistan","Skardu","gb","gen","uobs.edu.pk",""],
/* Azad Jammu & Kashmir */
["ajku","University of Azad Jammu & Kashmir","Muzaffarabad","ajk","gen","ajku.edu.pk",""],
["must","Mirpur University of Science & Technology (MUST)","Mirpur","ajk","eng","must.edu.pk",""],
["upr","University of Poonch","Rawalakot","ajk","gen","upr.edu.pk",""],
["uokajk","University of Kotli","Kotli","ajk","gen","uokajk.edu.pk",""],
["wuajk","Women University of AJK","Bagh","ajk","women","wuajk.edu.pk",""]
],

/* Fees and admission criteria. fee = undergraduate fee with its unit; once = one-time charges;
   session = which year the figure is for; src = [label, url]; conf = see top. */
detail: {
pu:{ fee:"Merit seats: PKR 15,750–55,000 tuition per semester. Self-supporting: PKR 47,300–132,500 per semester.", once:"First-semester services PKR 14,250 + registration PKR 9,000 + library security PKR 5,500 (refundable)", elig:"Intermediate; programme-wise minimums in the prospectus", test:"PU entry test (25% of merit); LAT for LLB", opens:"May–Jul", session:"2026-27", src:["PU dues & fee schedule 2026-27","https://pu.edu.pk/downloads/Dues-Fee-Schedule-for-the-Year-2026-27.pdf"], conf:"official" },
uet:{ fee:"BSc Engineering (subsidised): PKR 56,290 in semester 1, rising to PKR 105,060 by semester 8; about PKR 713,920 for the degree. Partially subsidised seats: about PKR 1,085,430 for the degree.", once:"Admission PKR 54,050 (subsidised) or PKR 74,040 (partially subsidised)", elig:"60% in Intermediate with Physics, Chemistry and Maths", test:"ECAT (33% of merit)", opens:"May–Jul", session:"Fall 2026", src:["UET admissions portal","https://admission.uet.edu.pk/program/1"], conf:"official" },
gcu:{ fee:"First semester about PKR 66,850 (humanities) to PKR 152,850 (BS Management); BSc Electrical Engineering PKR 145,550", once:"Application PKR 1,000", elig:"Merit on Intermediate Part-I marks", test:"No test for most BS programmes (BFA and Physical Education have tests)", opens:"Jul–Aug (Fall 2026 deadline 19 Aug)", session:"2026", src:["ProPakistani","https://propakistani.pk/2026/08/10/gc-university-lahore-opens-fall-2026-admissions-with-60-scholarship/"], conf:"secondary" },
qau:{ fee:"Latest official BS fee found is Fall 2021: regular about PKR 48,000–49,650 per semester, self-finance about PKR 89,870–90,970. Check QAU for the current fee.", once:"Processing PKR 2,200 (Fall 2024)", elig:"50% in HSSC Part-I", test:"HEC USAT (merit: Matric 30% + HSSC 70%)", opens:"Jun–Aug", session:"Fall 2021 fee / Fall 2024 policy", src:["QAU admission notice","https://qau.edu.pk/admissions-for-undergraduate-bs-ba-llb-pharm-d-morning-programme-on-regular-self-finance-basis-fall-semester-2024/"], conf:"old" },
nust:{ fee:"Engineering, computing, sciences: PKR 216,750 per semester (+ PKR 5,000 misc). Business, social sciences, architecture: PKR 302,950 per semester.", once:"Processing PKR 35,000 + security PKR 10,000 (refundable)", elig:"60% in Matric and FSc Part-I (engineering/computing)", test:"NET (75% of merit)", opens:"Oct–Jul, four NET series", session:"2026-27", src:["NUST undergraduate fees","https://nust.edu.pk/admissions/fee-structure/undergraduate-financial-matters/"], conf:"official" },
comsats:{ fee:"BS Computer Science PKR 144,500 per semester; BBA PKR 139,000; BS Engineering PKR 144,500; + registration PKR 7,000 per semester (Lahore campus)", once:"Admission PKR 22,000", elig:"50% Intermediate (CS with Maths); 60% for engineering", test:"NTS NAT", opens:"Fall: Jun–Aug; Spring: Dec–Jan", session:"Fall 2025", src:["COMSATS Lahore fee structure","https://lahore.comsats.edu.pk/admissions/fee/Fall2025FeeStructure.pdf"], conf:"official" },
pieas:{ fee:"2023 leaflet: about PKR 99,000 first semester, then PKR 59,000 per semester (hostel extra). Check the current fee page.", once:"Admission PKR 35,000; application PKR 3,500", elig:"60% in Matric and in Intermediate", test:"PIEAS test", opens:"Spring–summer", session:"2023 fee / 2026 leaflet", src:["PIEAS BS leaflet 2026","https://admissions.pieas.edu.pk/Admissions/Contents/Information%20leaflet%20BS-Programs-Updated_02012026.pdf"], conf:"old" },
ist:{ fee:"Engineering PKR 155,836–162,424 per semester; computing PKR 138,852; sciences PKR 91,416", once:"About PKR 49,000", elig:"Engineering: 60% in Matric and FSc Pre-Engineering; computing: HSSC with Maths", test:"NAT, NET, ECAT or IST test (engineering only)", opens:"Apr–Jun", session:"Fall 2026", src:["Maqsad guide","https://blog.maqsad.io/blog/ist-admission-guide"], conf:"secondary" },
iiui:{ fee:"University dues PKR 17,100–67,500 per semester (total PKR 24,100–74,500). E.g. Arabic 21,100; social sciences 30,450; CS 48,240; BS Engineering 52,200.", once:"Admission PKR 7,000 + library security PKR 7,000 (refundable)", elig:"See admission advertisement", test:"IIUI test for some programmes", opens:"Jun–Aug and Dec–Jan", session:"Spring 2026", src:["IIUI fee structure","https://admission.iiu.edu.pk/fee-structure"], conf:"official" },
air:{ fee:"Per credit hour: English/Psychology PKR 5,900; BBA PKR 7,650; CS/AI/Data Science PKR 9,150; BE PKR 8,050–8,600. Plus PKR 6,000 misc per semester.", once:"Processing 2,500 + admission 20,000 + endowment 5,000 + security 10,000", elig:"See admission advertisement", test:"Air University test", opens:"May–Aug", session:"Fall 2026", src:["Air University fees","https://webdata.au.edu.pk/Pages/Admission/fees_financial.aspx"], conf:"official" },
bahria:{ fee:"BBA about PKR 155,440–172,000 per semester; BS CS about PKR 162,745; engineering about PKR 145,200–157,760", once:"Admission PKR 30,000 + security PKR 22,000", elig:"50% Intermediate; 60% Pre-Engineering for engineering", test:"Bahria computer-based test, or SAT/HAT", opens:"From March", session:"Fall 2026", src:["Maqsad guide","https://blog.maqsad.io/blog/bahria-university-admission-guide"], conf:"secondary" },
numl:{ fee:"BS English about PKR 75,000 per semester; BBA about PKR 93,500; BS CS about PKR 97,010", once:"Not published", elig:"See NUML advertisement", test:"Not published", opens:"Jun–Aug", session:"2026", src:["ilmkidunya","https://www.ilmkidunya.com/colleges/national-university-of-modern-languages-islamabad-fee-structure.aspx"], conf:"secondary" },
aiou:{ fee:"PKR 17,900–54,950 per semester (humanities 17,900; IT 52,950)", once:"Not published", elig:"Intermediate; technical programmes need 50% with Maths", test:"None", opens:"Autumn: Jul; Spring: Jan–Feb", session:"Autumn 2025", src:["AIOU fee & eligibility","https://www.aiou.edu.pk/sites/default/files/2025-07/Fee%20&%20Eligibility%20Autumn%202025.pdf"], conf:"official" },
vu:{ fee:"PKR 935 per credit hour + PKR 1,000 enrolment per semester (about PKR 12,000 for a 12-credit semester)", once:"Admission PKR 3,000 + processing PKR 500", elig:"Intermediate", test:"None", opens:"Spring and Fall", session:"2023-24", src:["eduinfo.pk","https://eduinfo.pk/vu/fee-structure/"], conf:"secondary" },
uaf:{ fee:"BSc (Hons) Agriculture PKR 54,000 per semester; Biotechnology 84,000; Physics/Chemistry 78,000; CS 60,000 (after a 50%+ rise)", once:"Not published", elig:"Intermediate", test:"UAF entry test", opens:"Jun–Aug", session:"2026-27", src:["ProPakistani","https://propakistani.pk/2026/09/08/university-of-agriculture-faisalabad-raises-fees-by-over-50/"], conf:"news" },
bzu:{ fee:"BS English/CS/BBA about PKR 27,150 per semester; engineering PKR 43,650–45,850", once:"Not published", elig:"See BZU advertisement", test:"Not published", opens:"Jun–Jul", session:"2026", src:["Eduvision","https://www.eduvision.edu.pk/bahauddin-zakariya-university-multan-bzu-multan-ins-6"], conf:"secondary" },
iub:{ fee:"First semester total PKR 62,720–161,460 (BS English 62,720; CS 65,160; BBA 68,890; BSc Civil 65,000; Pharm-D up to 161,460)", once:"Included in first-semester totals", elig:"See IUB advertisement", test:"Not published", opens:"Jul–Aug", session:"Fall 2025", src:["IUB fee structure Fall 2025","https://www.iub.edu.pk/uploads/2340/admission-fall-2025/fee-fall-2025/1752586420-revised-fee-structure-fall-2025-for-new-intake-only.pdf"], conf:"official" },
uos:{ fee:"Tuition PKR 21,650–81,850 per semester; first semester e.g. BS English about PKR 43,000; BSc Civil about PKR 82,400", once:"Admission PKR 3,000 + registration PKR 5,000", elig:"See advertisement", test:"Not published", opens:"Jul–Sep", session:"Fall 2025", src:["UoS fee structure Fall 2025","https://su.edu.pk/upload/Fee%20Structure%20-%20Fall%202025.pdf"], conf:"official" },
gcuf:{ fee:"First semester: BS English PKR 30,800; BBA 45,800; BS CS 53,900; Pharm-D 74,200. Later semesters PKR 23,500–67,700.", once:"Admission 2,000 + registration 2,000 + library security 2,500", elig:"See advertisement", test:"Not published", opens:"Jul–Sep", session:"2025", src:["GCUF fee structure 2025","https://admissions.gcuf.edu.pk/downloads/2025/Fee-Structure-2025.pdf"], conf:"official" },
uog:{ fee:"About PKR 69,450–71,950 per semester", once:"Application PKR 200 per programme", elig:"45% (arts, social sciences), 50% (computing), 60% (engineering)", test:"Engineering: ECAT/NET/NTS/ETEA score (33% of merit); LAT for LLB", opens:"Jul–Sep", session:"Fall 2025", src:["UoG admission policy","https://uog.edu.pk/downloads/admissions/2025/Undergraduate_Admission_Policy_for_Fall-2025.pdf"], conf:"official" },
uok:{ fee:"About PKR 28,500–47,500 per semester for arts and sciences; CS about 94,500; BBA about 123,000", once:"Not published", elig:"Intermediate (open merit)", test:"Open merit for most; tests for some departments", opens:"Oct (2026: 12–21 Oct)", session:"2026", src:["ProPakistani","https://propakistani.pk/2026/09/24/karachi-university-announces-open-merit-bs-admissions-2026/"], conf:"secondary" },
ned:{ fee:"Regular seats PKR 57,000 per semester (about PKR 123,000 in the first semester). Self-finance PKR 890,000 and sponsored PKR 1,100,000 (+3% tax).", once:"Admission PKR 28,000", elig:"60% in HSC Pre-Engineering", test:"NED test (60% of merit; pass 50%)", opens:"Mar–May", session:"2026-27", src:["NED FAQ 2026","https://www.neduet.edu.pk/sites/default/files/Admissions-2026/FAQ.pdf"], conf:"official" },
iba:{ fee:"PKR 31,500 per credit hour (BBA and BS) + 3% sales tax", once:"Admission PKR 125,000; BBA activity charges PKR 7,000", elig:"Intermediate or A-levels (see IBA criteria)", test:"IBA aptitude test (3 rounds)", opens:"Nov–Jun", session:"Fall 2026", src:["IBA fee structure","https://iba.edu.pk/fee-structure.php"], conf:"official" },
sukkur:{ fee:"About PKR 106,000 per semester (BBA, BS and BE)", once:"Not published", elig:"Intermediate", test:"Sukkur IBA test", opens:"Apr–Jul", session:"2025", src:["Eduvision","https://www.eduvision.edu.pk/sukkur-iba-university-sibau-sukkur-ins-1301"], conf:"secondary" },
usindh:{ fee:"About PKR 23,000 per semester for most BS; CS/IT 24,500; engineering 33,500", once:"Application PKR 3,000", elig:"Intermediate", test:"Pre-entry test (pass 40%); LAT for LLB", opens:"Aug–Sep", session:"Admissions 2027", src:["Admissions 2027 advertisement","https://admission.usindh.edu.pk/admission/assets/advertisement_2027.pdf"], conf:"official" },
muet:{ fee:"Regular seats PKR 48,800 per semester (tuition 25,000). Self-finance seats charged separately by discipline.", once:"Admission 27,800 + caution money 6,600 + other 8,050 (PKR 42,450)", elig:"Intermediate Pre-Engineering (see advertisement)", test:"MUET pre-admission test", opens:"Apr–May", session:"Current page (undated)", src:["MUET fee structure","https://admissions.muet.edu.pk/admission-fees-structure/"], conf:"official" },
duhs:{ fee:"MBBS open merit: tuition PKR 48,000 a year; first-year total PKR 119,500. Self-finance: PKR 650,000 a year; first-year total PKR 768,895.", once:"Admission PKR 25,000 (merit) / PKR 50,000 (self-finance)", elig:"65% in FSc Pre-Medical, then pass MDCAT", test:"MDCAT", opens:"After MDCAT result", session:"2025-26", src:["DUHS prospectus 2025-26","https://admissions.duhs.edu.pk/doc/Prospectus%202025-26%20all%20Sindh%20Final-20251205.pdf"], conf:"official" },
uop:{ fee:"Roughly PKR 20,000–40,000 per semester (portal estimate; the official Fall 2025 PDF couldn't be read)", once:"Not published", elig:"See advertisement", test:"Not published", opens:"Jul–Sep", session:"Fall 2025", src:["ilmkidunya","https://www.ilmkidunya.com/colleges/university-of-peshawar-fee-structure.aspx"], conf:"secondary" },
uetp:{ fee:"Open merit: first semester about PKR 50,000–85,000, later PKR 25,000–70,000. Self-finance: first year about PKR 230,000–250,000. (Estimates.)", once:"Not published", elig:"60% in FSc Pre-Engineering", test:"ETEA", opens:"Jun–Aug", session:"2025-26", src:["Maqsad guide","https://blog.maqsad.io/blog/uet-fee-structure-2025"], conf:"secondary" },
kmu:{ fee:"KP public MBBS, open merit: KMC, KGMC and Ayub PKR 102,000 (year 1) to 135,520 (year 5); other colleges PKR 87,000 to 109,807. Self-finance PKR 1.16–1.55 million a year.", once:"Not published", elig:"65% in FSc Pre-Medical, then pass MDCAT", test:"MDCAT (held by KMU)", opens:"After MDCAT result", session:"2025-26", src:["Education in Karachi","https://educationinkarachi.net/kpk-public-medical-colleges-mbbs-fee-structure/"], conf:"secondary" },
uom:{ fee:"PKR 22,600 per semester (arts, BBA); PKR 29,000 (CS, AI, Pharm-D)", once:"Not published", elig:"See advertisement", test:"Not published", opens:"Jul–Sep", session:"2026", src:["Eduvision","https://www.eduvision.edu.pk/university-of-malakand-uom-chakdara-ins-41"], conf:"secondary" },
hu:{ fee:"PKR 38,980 per semester for most BS; CS/SE 41,300; LLB/Architecture 69,211; Pharm-D 93,147", once:"Not published", elig:"Intermediate pass (FSc, FA, ICS)", test:"Not published", opens:"Jul–Sep", session:"2026", src:["Eduvision","https://www.eduvision.edu.pk/hazara-university-hu-mansehra-ins-13"], conf:"secondary" },
uob:{ fee:"About PKR 28,266 per semester (arts); CS 30,000; sciences 35,120; Pharm-D 40,000", once:"Not published", elig:"See advertisement", test:"Not published", opens:"Aug–Oct", session:"2026", src:["Eduvision","https://www.eduvision.edu.pk/university-of-balochistan-uob-quetta-ins-37"], conf:"secondary" },
buitems:{ fee:"Engineering & ICT PKR 148,385 per semester; other programmes PKR 104,225", once:"Engineering PKR 62,920; others PKR 46,200 (includes refundable security)", elig:"See advertisement", test:"BUITEMS test", opens:"Jun–Aug", session:"Current page (undated)", src:["BUITEMS fee structure","https://www.buitms.edu.pk/Fee-Structure"], conf:"official" },
kiu:{ fee:"PKR 33,260–60,920 per semester; first semester PKR 41,760–69,420 (engineering up to 69,420)", once:"Admission 2,500 + registration 3,000 + security 3,000", elig:"See advertisement", test:"Not published", opens:"Jul–Sep", session:"2024-25", src:["KIU fee structure 2024-25","https://www.kiu.edu.pk/cms/wp-content/uploads/2024/08/Fee-Structure-2024-25-Annexure-B.pdf"], conf:"old" },
kemu:{ fee:"MBBS open merit is roughly PKR 20,000–50,000 a year (portal figure; UHS prospectus doesn't print fees)", once:"Not published", elig:"65% in FSc Pre-Medical; merit = Matric 10% + FSc 40% + MDCAT 50%", test:"MDCAT; central admission through UHS", opens:"After MDCAT result", session:"2025-26", src:["UHS prospectus 2025-26","https://www.uhs.edu.pk/downloads/Prospectus25-26.pdf"], conf:"secondary" },
uhs:{ fee:"Punjab public MBBS on open merit is roughly PKR 25,000–50,000 a year (portal figure; the UHS prospectus doesn't print fee amounts)", once:"Not published", elig:"65% in FSc Pre-Medical; merit = Matric 10% + FSc 40% + MDCAT 50%", test:"MDCAT; UHS runs central admission to all Punjab public medical colleges", opens:"After MDCAT result", session:"2025-26", src:["UHS prospectus 2025-26","https://www.uhs.edu.pk/downloads/Prospectus25-26.pdf"], conf:"secondary" },
awkum:{ fee:"Not published (official page lists only private BA/MA fees)", once:"Not published", elig:"See advertisement", test:"Not published", opens:"Jul–Sep", session:"—", src:["AWKUM fee page","https://awkum.edu.pk/admissions/fee-structure/"], conf:"official" },
ajku:{ fee:"Not published online", once:"Not published", elig:"See admission page", test:"Not published", opens:"Jul–Sep", session:"—", src:["UAJK admissions","https://umis.ajku.edu.pk/admissions"], conf:"official" }
}
};
