#!/usr/bin/env node
/*
 * Build police/data.js from data/police-stations.txt and the district list
 * on the Districts & Union Councils page (admin-units/index.html).
 *
 * Usage: node scripts/build_police.js
 */
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");

function grab(src, name) {
  const start = src.indexOf("const " + name + " = ");
  let j = src.slice(start).search(/[\[{]/) + start, depth = 0, quote = null;
  const open = j;
  for (; j < src.length; j++) {
    const c = src[j];
    if (quote) { if (c === "\\") { j++; continue; } if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'" || c === "`") { quote = c; continue; }
    if (c === "[" || c === "{") depth++;
    else if (c === "]" || c === "}") { depth--; if (!depth) break; }
  }
  return src.slice(open, j + 1);
}
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-");

/* districts */
const PROV = Function('"use strict";return (' + grab(read("admin-units/index.html"), "PROV") + ")")();
const provs = PROV.map((p) => ({
  id: p.id, name: p.name, ur: p.ur,
  divs: p.divs.map(([dn, , list]) => ({
    name: dn,
    districts: list.map(([line]) => { const [name, ur, hq] = line.split("|"); return { id: p.id + "-" + slug(name), name, ur, hq }; }),
  })),
}));
const known = new Set(provs.flatMap((p) => p.divs.flatMap((d) => d.districts.map((x) => x.id))));

/* official data */
const data = {};
let cur = null, problems = [];
read("data/police-stations.txt").split("\n").forEach((line, n) => {
  line = line.trim();
  if (!line || line.startsWith("# ") || line === "#") return;
  if (line.startsWith("## ")) {
    const [id, src, url] = line.slice(3).split("|").map((s) => s.trim());
    if (!known.has(id)) problems.push(`line ${n + 1}: unknown district id "${id}"`);
    cur = data[id] = { src, url, office: [], links: [], circles: [] };
    return;
  }
  if (!cur) return;
  if (line.startsWith("office:")) { cur.office.push(line.slice(7).split("|").map((s) => s.trim())); return; }
  if (line.startsWith("link:")) { cur.links.push(line.slice(5).split("|").map((s) => s.trim())); return; }
  if (line.startsWith("- ")) {
    const k = line.indexOf(":");
    const circle = line.slice(2, k).trim();
    const stations = line.slice(k + 1).split(";").map((s) => s.trim()).filter(Boolean).map((s) => { const [a, b] = s.split("|"); return [a.trim(), (b || "").trim()]; });
    cur.circles.push([circle, stations]);
  }
});
if (problems.length) { console.error(problems.join("\n")); process.exit(1); }

const PROV_LINKS = {
  pb: [["Punjab Police district offices", "https://punjabpolice.gov.pk/dpocontacts"], ["Punjab Police", "https://punjabpolice.gov.pk"]],
  sd: [["Karachi police stations (official)", "https://karachipolice.gov.pk/services/police-stations-in-karachi/"], ["Sindh Police", "https://sindhpolice.gov.pk"]],
  kp: [["KP Police station directory", "https://www.kppolice.gov.pk/phone-directory.php?tid=4"]],
  bl: [["Balochistan district police offices", "https://balochistanpolice.gov.pk/dpo_contactdetails"], ["Balochistan Police", "https://balochistanpolice.gov.pk"]],
  ict: [["Islamabad Police", "https://islamabadpolice.gov.pk/contact.php"]],
  ajk: [],
  gb: [["Gilgit-Baltistan Police", "https://gbp.gov.pk"]],
};

/* totals per district and stations found only on the map (data/police/stations.json, from scripts/police_process.py) */
const counts = {}, mapOnly = [];
const SJ = path.join(ROOT, "data/police/stations.json");
if (fs.existsSync(SJ)) {
  const sj = JSON.parse(fs.readFileSync(SJ, "utf8"));
  for (const [id, v] of Object.entries(sj)) {
    const located = v.stations.filter((s) => s.ll).length;
    if (v.stations.length) counts[id] = [v.stations.length, located];
    if (!data[id] || !data[id].circles.length) v.stations.forEach((s) => mapOnly.push([id, s.n, s.ph || ""]));
  }
}

const stations = Object.values(data).reduce((a, d) => a + d.circles.reduce((b, c) => b + c[1].length, 0), 0);
const listed = Object.values(data).filter((d) => d.circles.length).length;
const out = "/* Generated by scripts/build_police.js from data/police-stations.txt. Do not edit by hand. */\n" +
  "window.PS=" + JSON.stringify({ built: new Date().toISOString().slice(0, 10), provs, data, provLinks: PROV_LINKS, counts, mapOnly }) + ";\n";
fs.writeFileSync(path.join(ROOT, "police/data.js"), out);
console.log(`police/data.js: ${known.size} districts, ${listed} with official station lists, ${stations} stations`);
